### ISSUE TITLE
Visual Studio 14 crash

### ISSUE THREAD

**Issue by claudiuconstantin** [jakobehn/GitFlow.VS#56]
After installed in Visual Studio, the extension crashes when the "GitFlow" tab is accessed in Team Explorer pane.

![error 3](https://cloud.githubusercontent.com/assets/1537573/18552628/e637c846-7b65-11e6-82e9-42e619c664c7.png)

**Comment by kipusoep** [comment]
I've got sort of the same issue; reloading files in VS2015 causes VS2015 to crash with the same error in the event viewer:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at GitFlowVS.Extension.GitFlowInitSection.UpdateVisibleState()
   at GitFlowVS.Extension.GitFlowPage+<>c__DisplayClass10_0.<Refresh>b__1()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by jakobehn** [comment]
This bug should be fixed in the latest version for VS2017, I haven't yet rebuilt the VS2015 version.

You should not get this exception if you have connected to a Git repo, can you verify that? 

Thanks

**Comment by kipusoep** [comment]
For me re-installing the extension fixed the issue. I think it had something to do with installing and un-installing VS2017.

**Comment by scottkirwanthomas** [comment]
This still happens for me.  I have vs 2017 & 2015 installed. Git flow works fine on 2017 but fails with the above exception on 2015
